name: Command injection
options:
    difficulties:
        - Easy
        - Medium
        - Hard
    elements:
        - id: test
          label: Test checkbox
          type: checkbox
          checked: false
          modes:
            - Easy
            - Medium
        
        - id: debug
          label: Debug information
          type: text
          placeholder: sdfsdfs
          modes:
            - Hard
            - Elite
        
        - id: select_test
          label: test selector
          type: select
          default: Item 2
          values:
            - Item 1
            - Item 2
            - Item 3
        
        - id: radio_test
          label: Radio buttons
          type: radio
          default: ee
          buttons:
            - id: ee
              label: eee
            - id: rr
              label: eee
