#!/bin/bash

next_user=$(get-from-context "next-user")
difficulty=$(get-from-context "difficulty")
open_source=$(get-from-context "open_source")

# Parse the template and compile the challenge
parse-template challenge.j2 challenge.c
gcc challenge.c -o challenge -fstack-protector-all -z,now,-z,noexecstack,-z,relro

set-default-ownership .

chmod 555 challenge

if [ "${open_source}" == "on" ]; then
    chmod 444 challenge.c
else
    chmod 000 challenge.c
fi

add-wrapper challenge sguid
# Uncomment for CTF mode
# add-wrapper challenge password
