name: SQL Injection
options:
    difficulties:
        - Direct
        - Blind
    elements:
        - id: open_source
          label: Access to challenge source file
          type: checkbox
          checked: false
        - id: username_buffer_size
          label: Username buffer size
          type: text
          placeholder: buffer size
          value: 128