#!/bin/bash

generate-flag --output /challenge/end/flag.txt

# Parse the template and compile the challenge
parse-template template.c \
            -c "gcc challenge.c -Wall -o challenge -fno-stack-protector" \
            -o challenge.c