#!/bin/bash
next_user=$(get-step-config "next-user")
difficulty=$(get-step-config "difficulty")
step_switch=$(get-step-config "step-switch")

# Parse the template and compile the challenge
parse-template challenge.j2 challenge.c
gcc challenge.c -o challenge

chown -R "$next_user":worker .
chmod 440 challenge.c

if [ $step_switch != "custom" ]
then
    add-wrapper challenge
else
    chmod 550 challenge
fi