#!/bin/bash

# Configuration has to be done directly onto the student container
ssh_student --user step1 --script-as-root --setup-script "generate-steps"
check-flag --student-flag-path /task/student/answer --correct-flag-path /task/student/end/flag