name: Basic Buffer Overflow
options:
    difficulties:
        - Easy
        - Medium
        - Hard
    elements:
        - id: test
          label: Test checkbox
          type: checkbox
          checked: false
          modes:
            - Easy
            - Medium
        
        - id: debug
          label: Debug information
          type: text
          placeholder: sdfsdfs
          modes:
            - Hard
            - Elite
