#!/bin/bash

next_user=$(get-step-config "next-user")
difficulty=$(get-step-config "difficulty")

# Parse the template and compile the challenge
parse-template challenge.j2 challenge.c
gcc challenge.c -Wall -o challenge -fno-stack-protector

chown -R "$next_user" .
chgrp -R worker .
chmod 440 challenge.c

add-wrapper challenge