#!/bin/bash

# Generate a random flag
generate-flag --output /task/student/flag.txt

# Disable ASLR
echo 0 > /proc/sys/kernel/randomize_va_space

# Parse the template and compile the challenge
parse-template /task/student/scripts/template.c \
            -c "gcc /task/student/challenge.c -O0 -o /task/student/challenge -fno-stack-protector" \
            -o /task/student/challenge.c

# Set the UID bit
chmod u+s /task/student/challenge

ssh_student

check-flag --student-flag-path /task/student/answer.txt --correct-flag-path /task/student/flag.txt