#!/bin/bash

chown end challenge database.db
chmod g+x . # challenge owner needs execute permissions on database folder to use database
chmod 440 challenge.c
chmod 400 database.db
chmod 550 challenge
chmod u+s challenge
