#!/bin/bash

# Parse the template and compile the challenge
parse-template challenge.j2 challenge.c
gcc challenge.c -Wall -o challenge -fno-stack-protector

set-default-permissions .
chmod 440 challenge.c

add-wrapper challenge shell-python
