#!/bin/bash

difficulty=$(get-from-context "difficulty")

# Parse the template and compile the challenge
parse-template challenge.j2 challenge.c
gcc challenge.c -o challenge -fno-stack-protector -no-pie -z,now,-z,noexecstack,-z,norelro

set-default-ownership .

if [ "${difficulty}" == "Easy" ]; then
    chmod 444 challenge.c
else
    chmod 000 challenge.c
fi

add-wrapper challenge shell-python
