name: Buffer Overflow - Flow control
options:
    difficulties:
        - Redirect
        - Stack
        - Lib-C
        - ROP
    elements:
        - id: bits
          label: 32 bit executable
          type: checkbox
          value: false
        - id: open_source
          label: Access to challenge source file
          type: checkbox
          checked: false
        - id: show_compilation
          label: Give the compilation command to the user
          type: checkbox
          checked: false
