#!/bin/bash

python3 database_gen.py

# Parse the template and compile the challenge
parse-template template.c \
            -c "gcc challenge.c -Wall -o challenge -l sqlite3" \
            -o challenge.c
