#!/bin/bash

next_user=$(get-step-config "next-user")

# Parse the template and compile the challenge
parse-template challenge.j2 challenge.c
gcc -Wall challenge.c -o challenge

chown -R "${next_user}" .
chgrp -R worker .
chmod 000 challenge.c
chmod u+s challenge
