#!/bin/bash

next_user=$(get-step-config "next-user")
difficulty=$(get-step-config "difficulty")

# Parse the template and compile the challenge
# parse-wrap challenge.j2 challenge.c challenge -i "gcc -Wall -o challenge challenge.c"
parse-template challenge.j2 challenge.c
gcc -Wall challenge.c -o challenge 
add-wrapper challenge

chgrp -R worker .
chmod 000 challenge.c