#!/bin/bash

next_user = get-config "next-user"
difficulty = get-config "difficulty"

# Parse the template and compile the challenge
parse-template "challenge.tpl" -o "challenge.c"

chown $next_user challenge
chmod 000 challenge.c
chmod 550 challenge
chmod u+s challenge